services:
    mariadb:
        container_name: mariadb42
        image: mariadb:42
        build: ./requirements/mariadb
        restart: always
        env_file:
            - .env
        volumes:
            - mariadb_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - internet
    nginx:
        depends_on:
            - wordpress
            - mariadb
        container_name: nginx42
        image: nginx:42
        build: ./requirements/nginx
        restart: always
        env_file:
            - .env
        ports:
            - "80:80"
        networks:
            - internet
        volumes:
            - nginx_home:/var/www/html
    wordpress:
        depends_on:
            - mariadb
        container_name: wordpress42
        image: wordpress:42
        build: ./requirements/wordpress
        restart: always
        env_file:
            - .env
        ports:
            - "8000:80"
        networks:
            - internet
        volumes:
            - nginx_home:/var/www/html

networks:
    internet:
        driver: bridge


volumes:
    mariadb_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "~/inception_final/data/mariadb"
    nginx_home:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "~/inception_final/data/nginx"
