services:
    mariadb:
        container_name: mariadb42
        image: mariadb:42
        build: ./requirements/mariadb
        restart: always
        env_file:
            - .env
        volumes:
            - mariadb_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - internet
    nginx:
        container_name: nginx42
        image: nginx:42
        build: ./requirements/nginx
        restart: always
        env_file:
            - .env
        ports:
            - "80:80"
        networks:
            - internet

networks:
    internet:
        driver: bridge


volumes:
    mariadb_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "~/inception_final/data/mariadb"
